### ISSUE TITLE
when a guest user hits on checkout button in the second time for purchasing the product then it's through an error

### ISSUE THREAD

**Issue by anilahy** [DivanteLtd/magento2-external-checkout#4]
@pkarw
there is an issue when adding product as a guest user and completing the checkout form magento2
it works for the first time but repeating the same thing with gust user it gives a fatal error

**Comment by pkarw** [comment]
Thanks for the report. Please provide us with the fatal error you're getting in this case

**Comment by anilahy** [comment]
Fatal Error:
![38014544-beda03a2-3286-11e8-8f45-d264540d7858](https://user-images.githubusercontent.com/36910443/38019613-b5a65704-3295-11e8-96c8-48d96a2d9695.png)

**Comment by anilahy** [comment]
fatal error : 
Fatal error: Uncaught TypeError: Return value of Divante\CartSync\Service\Sync::synchronizeGuestCart() must implement interface Divante\CartSync\Service\SyncInterface, boolean returned in /var/www/html/magento24/app/code/Divante/CartSync/Service/Sync.php:146 Stack trace: #0 /var/www/html/magento24/app/code/Divante/CartSync/Controller/Cart/Sync.php(105): Divante\CartSync\Service\Sync->synchronizeGuestCart('dface673e17a45e...') #1 /var/www/html/magento24/generated/code/Divante/CartSync/Controller/Cart/Sync/Interceptor.php(24): Divante\CartSync\Controller\Cart\Sync->execute() #2 /var/www/html/magento24/vendor/magento/framework/App/Action/Action.php(107): Divante\CartSync\Controller\Cart\Sync\Interceptor->execute() #3 /var/www/html/magento24/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) #4 /var/www/html/magento24/vendor/magento/framework/Interception/Interceptor.php(138): Divante\CartSync\Controller\Cart\Sync\Interceptor->

**Comment by pkarw** [comment]
https://github.com/DivanteLtd/magento2-external-checkout/pull/5/files

Please check this fix

**Comment by pkarw** [comment]
I've added a feature request #7 that will solve the issue
